name: Build and Deploy Flutter Web with Rust

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Flutter pub get
        run: flutter pub get

      - name: Get repo name
        id: vars
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Build Flutter Web
        run: flutter build web --base-href "/${{ env.REPO_NAME }}/"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build Rust to Wasm
        run: |
          cd rust
          wasm-pack build --target web --out-dir ../build/web/pkg

      #- name: Copy Wasm pkg into Flutter Web build
      #  run: cp -r web/pkg build/web/pkg

      - name: Prepare deploy directory
        run: |
          mkdir -p deploy
          # pkg以外をdeployにコピー
          rsync -av --exclude=pkg/ build/web/ deploy/
          # pkgディレクトリ構造ごとコピー
          rsync -av build/web/pkg/ deploy/build/web/pkg/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy


     